let g:copilot_filetypes = {
      \ 'xml': v:false,
      \ 'yml': v:true,
      \ 'yaml': v:true,
      \ '*': v:false,
      \ 'php': v:true,
      \ 'js': v:true,
      \ 'javascript': v:true,
      \ 'html': v:true,
      \ 'css': v:true,
      \ 'scss': v:true,
      \ 'python': v:true,
      \ 'cpp': v:true,
      \ 'jsx': v:true,
      \ 'typescriptreact': v:true,
      \ 'typescript': v:true,
      \ 'c': v:true,
      \}
