version: '3'
services:
  jenkins:
    container_name: 'pipeline-jenkins'
    build:
      context: ./jenkins
      args:
        USER_ID: ${USER_ID}
        GROUP_ID: ${GROUP_ID}
    labels:
      kompose.service.type: nodeport
    environment:
      JENKINS_HOME: /jenkins_home
      WORKSPACE_PUID: 1000 
      WORKSPACE_PGID: 1000
    ports:
      - '8084:8080'
      - '8444:8443'
      - '50001:50000'
    volumes:
      - '/srv/pipeline/data/jenkins/jenkins_data:/jenkins_home'
      - '/var/run/docker.sock:/var/run/docker.sock'
      - '/srv/pipeline/data/jenkins/jenkins:/var/jenkins_config'
      - '/srv/pipeline/data/jenkins/data:/home/jenkins'
    networks:
      pipeline:
          ipv4_address: '172.20.0.2'

  srv_dev:
    container_name: srv_dev
    build:
      context: ./debian
      args:
        USER_ID: ${USER_ID}
        GROUP_ID: ${GROUP_ID}
    volumes:
      - '/sys/fs/cgroup:/sys/fs/cgroup:ro'
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
    expose:
      - '2221'
    networks:
      pipeline:
          ipv4_address: '172.20.0.6'
  registry:
    restart: always
    image: registry:2.7.0
    container_name: "pipeline-registry"
    ports:
      - 5000:5000
    networks:
      pipeline:
          ipv4_address: '172.20.0.3'
    environment:
      REGISTRY_HTTP_TLS_CERTIFICATE: /certs/myregistry.crt
      REGISTRY_HTTP_TLS_KEY: /certs/myregistry.key
      REGISTRY_AUTH: htpasswd
      REGISTRY_AUTH_HTPASSWD_PATH: /auth/htpasswd
      REGISTRY_AUTH_HTPASSWD_REALM: Registry Realm
    volumes:
      - /srv/pipeline/data/registry/data:/var/lib/registry
      - /srv/pipeline/data/registry/certs:/certs
      - /srv/pipeline/data/registry/passwd:/auth

  gitlab:
    image: 'gitlab/gitlab-ce:latest'
    restart: always
    hostname: 'gitlab.ritelg.com'
    container_name: "pipeline-gitlab"
    ports:
      - '8082:80'
      - '4433:443'
      - '2222:22'
    networks:
      pipeline:
          ipv4_address: '172.20.0.4'
    volumes:
      - '/srv/pipeline/data/gitlab/config:/etc/gitlab'
      - '/srv/pipeline/data/gitlab/logs:/var/log/gitlab'
      - '/srv/pipeline/data/gitlab/data:/var/opt/gitlab'
  gitlabRunner:
    image: 'ritelg/gitlab-runner:latest'
    restart: always
    container_name: "pipeline-gitlab-runner"
    networks:
      pipeline:
          ipv4_address: '172.20.0.5'
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
      - '/srv/pipeline/data/gitlab-runner:/etc/gitlab-runner'
      - '/srv/pipeline/data/.ssh:/root/.ssh'
      - '/srv/pipeline/data/.ssh:/home/gitlab-runner/.ssh'
networks:
  pipeline:
    ipam:
      driver: default
      config:
          - subnet: 172.20.0.0/16


##########################::
## Launch : docker-compose up -d registry srv_dev jenkins dind gitlabRunner && sudo docker-compose up -d gitlab
## Jenkins : 
##    mkdir -p /srv/data/jenkins/{jenkins_data, jenkins} 
##    touch /srv/data/jenkins/.dockercfg
##    creer clé ssh dans le container et la copié dans vagrant 
##      ssh-keygen -t rsa -b 4096 -f /home/jenkins/.ssh/id_rsa
##      ssh-copy-id -i ~/.ssh/id_rsa.pub vagrant@192.168.5.3
##      
##    Configurer ~/.ssh/config
##    Host IP_VAGRANT
##        PreferredAuthentications publickey
##        User vagrant
##        IdentityFile ~/.ssh/id_rsa
##        AddKeysToAgent yes
##  
##  
## Registry :
##    mkdir -p /srv/data/registry/{data,certs,passwd}
##    docker run --entrypoint htpasswd registry:2.7.0 -Bbn ritelg password > /srv/data/registry/passwd/htpasswd
##    openssl req -x509 -newkey rsa:4096 -nodes -keyout certs/myregistry.key -out certs/myregistry.crt -days 365 -subj /CN=myregistry.my
##    docker login 127.0.0.1:5000 -u USERNAME
##    "127.0.0.1:5000 myregistry" >> /etc/hosts
##
## Gitlab :
##    mkdir -p /srv/data/gitlab/{config,data,logs}
##    sudo docker-compose up -d gitlab
##    Creation clé SSH et ajout
##
##    https://www.sheevaboite.fr/articles/installer-gitlab-5-minutes-docker/
##
##    Ajout de 127.0.0.1 gitlab.ritelg.com dans /etc/hosts
##
##    Config ssh ~/.ssh/config :
##          Host gitlab.ritelg.com
##              Port 2222
##              HostName 127.0.0.1
##              Identityfile chemin cle ssh
##
## Gitlab Runner :
##    générés clés SSH dans /srv/data/.ssh : ssh-keygen -t rsa -b 4096 -f 
##    https://www.sheevaboite.fr/articles/installer-gitlab-ci-moins-5-minutes-docker/
##    Aller dans la page d'admin runner de gitlab : http://localhost:8080/admin/runners
##    docker exec -it gitlab-runner gitlab-runner register -u http://gitlab:80 --name "description" --tag-list tags -r token  --executor docker --docker-image image --non-interactive
##
##
##########################
