- name: Installation localhost
  hosts: localhost
  connection: local
  tasks:
    - name: Installation des paquets de bases
      apt: 
        name: 
          - fish
          - git 
          - curl
          - wget
          - silversearcher-ag
          - ripgrep
          - unzip 
          - tmux
          - fd-find
          - gnupg
          - ca-certificates
          - apt-transport-https
          - software-properties-common
          - python3-pip
          - virtualenv
          - python3-setuptools
        state: latest

    - include_vars: 
        file: vars.yml
    - name: Installation de docker
      include: docker.yml
