- name: Installation de docker
  file: 
    path: /etc/apt/keyrings
    mode: '0755'
    state: directory

- name: Ajout de la cle GPG
  ansible.builtin.get_url:
    url: https://download.docker.com/linux/debian/gpg
    dest: /etc/apt/keyrings/docker.gpg

- command: gpg --dearmor /etc/apt/keyrings/docker.gpg

- name: Ajout du repo
  apt_repository: 
    repo: deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/debian bullseye stable
    state: present 
    filename: docker


- name: Installation des paquets
  apt: 
    name: 
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    state: present
- name: Ajout du groupe docker
  ansible.builtin.group:
    name: docker
    state: present
- name: Assignation du groupe docker
  ansible.builtin.user:
    name: "{{ user }}"
    groups: docker
    append: yes
