---
- name: Installation du serveur
  hosts: all
  remote_user: root
  tasks:
  - include_vars:
      file: vars.yml
  - user:
      name: "{{ user }}"
      shell: /bin/bash
  - name: USER | Clef SSH
    authorized_key:
      user: "{{ user }}"
      state: present
      key: "{{ lookup('file', key) }}"
  - name: "USER | Sudoers {{ user }}"
    lineinfile:
      dest: /etc/sudoers
      state: present
      regexp: "^{{ user }}"
      line: '{{ user }} ALL=(ALL) NOPASSWD: ALL'
      validate: 'visudo -cf %s'
  - name: APT | Update & Upgrade
    command: apt-get update
    command: apt-get upgrade -y
...