# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
    config.vm.box = "debian/buster64"
    config.vm.hostname = "tuto-ansible"
    config.vm.network :private_network, ip: "192.168.6.2"
    config.vm.provision "shell" do |s|
        ssh_pub_key = File.readlines("#{Dir.home}/.ssh/id_rsa.pub").first.strip
        s.inline = <<-SHELL
            echo #{ssh_pub_key} >> /home/vagrant/.ssh/authorized_keys
            mkdir -p /root/.ssh
            touch /root/.ssh/authorized_keys
            echo #{ssh_pub_key} >> /root/.ssh/authorized_keys
            sudo apt-get install python -y
        SHELL
    end
    config.vm.provider :virtualbox do |v|
        v.memory = 2048
        v.cpus = 1
    end
    if Vagrant.has_plugin?("vagrant-cachier")
        p1jenkins.cache.scope = :box
    end
end