FROM ritelg/php:8.4-fpm

ARG USER_ID=1000 
ARG GROUP_ID=1000
RUN groupadd -f --gid $GROUP_ID user
RUN adduser --disabled-password --gecos '' --uid $USER_ID --gid $GROUP_ID user
USER user

EXPOSE 9000
