---
- name: TOOLS | Installations de Git, zsh, vim, pm2
  apt:
    name:
      - vim
      - zsh
      - git
      - tmux
      - unzip
    state: present

- include: zsh-task.yml
- include: vim-task.yml

...
