version: '3.1'
services:
  web:
    container_name: dev_web
    image: nginx:latest
    ports:
      - 8000:80
    volumes:
      - ..:/var/www:delegated
      - ./site.conf:/etc/nginx/conf.d/default.conf
    links:
      - php
  php:
    container_name: dev_php
    build:
      context: ./php
      args:
        USER_ID: ${USER_ID}
        GROUP_ID: ${GROUP_ID}
    volumes:
      - ..:/var/www:delegated
#    links:
#      - db
#      - mail
    environment:
      PHP_IDE_CONFIG: serverName=ritelg
  php_test:
    container_name: test_php
    environment:
      WAIT_HOSTS: dbtest:5432
    build:
      context: ./docker/php
      args:
        USER_ID: ${USER_ID}
        GROUP_ID: ${GROUP_ID}
    volumes:
      - ..:/var/www:delegated
#  db:
#    container_name: dev_db
#    image: mysql
#    volumes:
#      - db-data:/var/lib/mysql
#    restart: always
#    environment:
#      MYSQL_ROOT_PASSWORD: root
#      MYSQL_DATABASE: enjoy_events
#      MYSQL_USER: enjoy_events
#      MYSQL_PASSWORD: enjoy_events
#    ports:
#    - 3307:3306
#  adminer:
#    container_name: dev_adminer
#    image: adminer
#    environment:
#      ADMINER_DESIGN: arcs-material
#      ADMINER_DEFAULT_SERVER: pgsql
#    links:
#      - db
#    ports:
#      - 8888:8080
#   mail:
#     container_name: dev_mail
#     image: djfarrelly/maildev
#     ports:
#       - 1080:1080


volumes:
  db-data:
    driver: local
