---
- name: Installer la clé GPG (dearmor) pour griffo
  ansible.builtin.shell: |
    set -euo pipefail
    curl -fsSL https://debian.griffo.io/EA0F721D231FDD3A0A17B9AC7808B4DD62C41256.asc \
      | gpg --dearmor --yes -o /etc/apt/trusted.gpg.d/debian.griffo.io.gpg
  args:
    creates: /etc/apt/trusted.gpg.d/debian.griffo.io.gpg

- name: Ajouter le dépôt APT pour griffo
  ansible.builtin.apt_repository:
    repo: "deb https://debian.griffo.io/apt  ansible_distribution_release  main"
    filename: "debian.griffo.io"
    state: present

- name: apt update
  ansible.builtin.apt:
    update_cache: true

- name: installer ghostty
  ansible.builtin.apt:
    name: ghostty
    state: present
